### ISSUE TITLE
FC - FunctionComponent and React v18 Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes'.

### ISSUE THREAD

**Issue by mkhomytsya** [nickovchinnikov/coursesbox#50]
Unfortunately, there are changes in FC component which  are not work with React V18,
would be nice to have proper elegant solution how to upgrade your tutorial runnable at latest React V18

**Comment by nickovchinnikov** [comment]
Hi @mkhomytsya, check this out
https://github.com/nickovchinnikov/minesweeper/issues/78

I have no time to update types and add a video lesson about it, sorry

**Comment by mkhomytsya** [comment]
> Hi @mkhomytsya, check this out [nickovchinnikov/minesweeper#78](https://github.com/nickovchinnikov/minesweeper/issues/78)
> 
> I have no time to update types and add a video lesson about it, sorry

Great! Thanks for quick answer!
